import type { LearningTool } from '../types'

export function Practice({dueCount,newCount,onStart,onOpenTool}:{dueCount:number;newCount:number;onStart:()=>void;onOpenTool:(tool:LearningTool)=>void}){
  const count=dueCount||Math.min(newCount,7)
  const title=dueCount?'Повторение готово':newCount?'Можно изучить новое':'Сейчас очередь пуста'
  const button=dueCount?'Начать повторение':newCount?'Начать новую сессию':'Очередь пуста'
  const canStart=dueCount>0||newCount>0
  return <div className="page generic-page"><p className="eyebrow">RETRIEVE · LISTEN · PRODUCE</p><h1>Практика</h1><p className="page-lead">Здесь язык перестаёт быть просто знакомым и становится доступным по памяти и в собственной речи.</p><div className="practice-feature"><div className="practice-orbit"><span>{count}</span><small>{dueCount?'due':newCount?'new':'clear'}</small></div><div className="practice-copy"><p className="eyebrow">ADAPTIVE REVIEW · FSRS</p><h2>{title}</h2><p>Сначала попытка вспомнить, потом ответ и звук. Следующая дата рассчитывается из истории конкретного элемента.</p><button className="primary-button" onClick={onStart} disabled={!canStart}>{button}</button></div></div><div className="feature-grid actionable-features"><Feature icon="⌁" title="Мои ошибки" text="Повторяющиеся ошибки превращаются в отдельную программу." onClick={()=>onOpenTool('errors')}/><Feature icon="◎" title="Говорение и письмо" text="Spaced task repetition: ответ → feedback → похожая задача позже." onClick={()=>onOpenTool('production')}/><Feature icon="✦" title="sENG Coach" text="Персональная миссия из твоих ошибок, Inbox и текущей цели." onClick={()=>onOpenTool('coach')}/><Feature icon="A" title="Активный словарь" text="Проверяй, что действительно дошло от узнавания до использования." onClick={()=>onOpenTool('active')}/></div></div>
}
function Feature({icon,title,text,onClick}:{icon:string;title:string;text:string;onClick:()=>void}){return <button className="feature-card feature-button" onClick={onClick}><span>{icon}</span><h3>{title}</h3><p>{text}</p><small>Открыть →</small></button>}
