import { useMemo,useState } from 'react'
import { learningItems } from '../data/seed'
import { formatNextReview } from '../lib/srs'
import type { LearningItem,MemoryState,ReviewRating } from '../types'
interface Props{items?:LearningItem[];memory:Record<string,MemoryState>;onRate:(itemId:string,rating:ReviewRating)=>void;onClose:()=>void}
const labels:Record<ReviewRating,{title:string;hint:string}>={again:{title:'Ещё раз',hint:'Не вспомнил'},hard:{title:'Трудно',hint:'Еле вспомнил'},good:{title:'Хорошо',hint:'Вспомнил'},easy:{title:'Легко',hint:'Автоматически'}}
export function StudySession({items=learningItems,memory,onRate,onClose}:Props){const[index,setIndex]=useState(0);const[revealed,setRevealed]=useState(false);const[finished,setFinished]=useState(false);const queue=useMemo(()=>items.length?items:learningItems.slice(0,5),[items]);const item=queue[index%queue.length];const rate=(rating:ReviewRating)=>{onRate(item.id,rating);if(index+1>=Math.min(queue.length,7))setFinished(true);else{setIndex(value=>value+1);setRevealed(false)}};if(finished)return <div className="study-overlay" role="dialog" aria-modal="true"><div className="study-sheet finish-card"><div className="success-orbit">✓</div><p className="eyebrow">SESSION COMPLETE</p><h2>Не просто посмотрел — вспомнил.</h2><p>Ответы уже повлияли на будущие интервалы. Следующая сессия будет немного другой.</p><button className="primary-button" onClick={onClose}>Вернуться на главную</button></div></div>;const currentMemory=memory[item.id];return <div className="study-overlay" role="dialog" aria-modal="true" aria-label="Учебная сессия"><div className="study-sheet"><header className="study-header"><button className="icon-button" onClick={onClose} aria-label="Закрыть">×</button><div className="session-progress"><span style={{width:`${((index+1)/Math.min(queue.length,7))*100}%`}}/></div><span className="counter">{index+1}/{Math.min(queue.length,7)}</span></header><div className="study-kind">{kindName(item)}</div><div className="study-card"><p className="study-prompt-label">Вспомни самостоятельно</p><h1>{item.prompt}</h1>{item.kind==='word'&&<button className="sound-button" onClick={()=>speak(item.answer)}>◖)) Слушать</button>}{!revealed?<button className="reveal-button" onClick={()=>setRevealed(true)}>Показать ответ</button>:<div className="answer-area"><div className="answer-main"><strong>{item.answer}</strong><span>{item.translation}</span></div><p className="example">“{item.example}”</p>{item.note&&<p className="note">⌁ {item.note}</p>}{currentMemory&&<p className="next-review">Было запланировано: {formatNextReview(currentMemory.dueAt)}</p>}</div>}</div>{revealed&&<div className="rating-grid">{(Object.keys(labels) as ReviewRating[]).map(rating=><button key={rating} className={`rating rating-${rating}`} onClick={()=>rate(rating)}><strong>{labels[rating].title}</strong><small>{labels[rating].hint}</small></button>)}</div>}</div></div>}
function kindName(item:LearningItem){if(item.kind==='irregular')return'НЕПРАВИЛЬНЫЙ ГЛАГОЛ';if(item.kind==='chunk')return'ЖИВОЕ ВЫРАЖЕНИЕ';return'СЛОВО В КОНТЕКСТЕ'}
function speak(text:string){if(!('speechSynthesis' in window))return;window.speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(text);utterance.lang='en-US';utterance.rate=.92;window.speechSynthesis.speak(utterance)}
